config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get  'help' => 'static_pages#help'
  get  'about' => 'static_pages#about'
  get  'contact' => 'static_pages#contact'
  get  'signup' => 'users#new'
  get  'rate' => 'ratings#new'
  get  'add_beer' => 'beers#new'
  get  'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get  'new_analysis' => 'analysis#new'
  get  'show_analysis' => 'analysis#show'
  post  'show_analysis' => 'analysis#show'
  resources :users
  resources :ratings
  resources :beers do
    collection { post:import}
  end
end

app/controllers/analysis_controller.rb
class AnalysisController < ApplicationController
  before_action :admin_user,     only: [:show, :new]
  
  def new
  end

  def show
    gon.data = []
    gon.xdata = []
    gon.y1data = []
    gon.y2data = []
    case params[:choice]
    when "best_beer"
      @chart_type = 'graph'
      gon.title = "Best Overall Rated Beers"
      gon.subtitle = "Top 10 beers rated from best to worst based on average rating"
      gon.y_title = "Rating Average (300 max)"
      gon.tooltip  = 'Rating Average: <b>{point.y}</b>'
      data_set = Beer.all.order(total_rating_avg: :desc).where.not(total_rating_avg: nil).limit(10)
      data_set.each do |i|
        gon.data << [i.name, i.total_rating_avg.to_f]
      end
    when "worst_beer"
      @chart_type = 'graph'
      gon.title = "Worst Overall Rated Beers"
      gon.subtitle = "Lowest 10 beers rated from best to worst based on average rating"
      gon.y_title = "Rating Average (300 max)"
      gon.tooltip  = 'Rating Average: <b>{point.y}</b>'
      data_set = Beer.all.order(total_rating_avg: :asc).where.not(total_rating_avg: nil).limit(10)
      data_set.each do |i|
        gon.data << [i.name, i.total_rating_avg.to_f]
      end
    when "most_rated_beer"
      @chart_type = 'graph'
      gon.title = "Most Rated Beers"
      gon.subtitle = "Top 10 most rated beers from most to least"
      gon.y_title = "Total Number of Ratings"
      gon.tooltip = 'Number of times rated: <b>{point.y}</b>'
      data_set = Beer.all.order(rating_count: :desc).where("rating_count > ?", 0).limit(10)
      data_set.each do |i|
        gon.data << [i.name, i.rating_count]
      end
    when "best_rated_1_beer"
      @chart_type = 'graph'
      gon.title = "Beers With the Best First Impression"
      gon.subtitle = "Top 10 most rated beers visually and for their aroma based on average rating"
      gon.y_title = "Rating Average (100 max)"
      gon.tooltip = 'Total Rating Avg: <b>{point.y}</b>'
      data_set = Beer.all.order(rating1_avg: :desc).where.not(rating1_avg: nil).limit(10)
      data_set.each do |i|
        gon.data << [i.name, i.rating1_avg.to_f]
      end
    when "best_rated_2_beer"
      @chart_type = 'graph'
      gon.title = "Beers With the Best Taste Rating"
      gon.subtitle = "Top 10 most rated beers for their taste based on average rating"
      gon.y_title = "Rating Average (100 max)"
      gon.tooltip = 'Average Rating: <b>{point.y}</b>'
      data_set = Beer.all.order(rating2_avg: :desc).where.not(rating2_avg: nil).limit(10)
      data_set.each do |i|
        gon.data << [i.name, i.rating1_avg.to_f]
      end
    when "best_rated_3_beer"
      @chart_type = 'graph'
      gon.title = "Beers With the Best After-taste"
      gon.subtitle = "Top 10 most rated beers for their after-taste and fill based on average rating"
      gon.y_title = "Rating Average (100 max)"
      gon.tooltip = 'Average Rating: <b>{point.y}</b>'
      data_set = Beer.all.order(rating3_avg: :desc).where.not(rating3_avg: nil).limit(10)
      data_set.each do |i|
        gon.data << [i.name, i.rating3_avg.to_f]
      end
    when "combo_rated"
      @chart_type = 'xy'
      gon.title = "Overall Average Rating vs Times Rated"
      gon.subtitle = "Combination Graph of Average Rating vs Number of Times Rated ordered by best rating"
      gon.y1title = "Rating Average (300 max)"
      gon.y2title = "Number of times rated"
      gon.y1name = "Average Rating"
      gon.y2name = "Times Rated"
      data_set = Beer.all.order(total_rating_avg: :desc).where.not(total_rating_avg: nil).limit(10)
      data_set.each do |i|
        gon.xdata << [i.name]
        gon.y1data << [i.total_rating_avg.to_f]
        gon.y2data << [i.rating_count]
      end
    when "combo_rated_reversed"
      @chart_type = 'xy'
      gon.title = "Overall Average Rating vs Times Rated"
      gon.subtitle = "Combination Graph of Average Rating vs Number of Times Rated ordered by most rated"
      gon.y1title = "Rating Average (300 max)"
      gon.y2title = "Number of times rated"
      gon.y1name = "Average Rating"
      gon.y2name = "Times Rated"
      data_set = Beer.all.order(rating_count: :desc).where.not(rating_count: nil).limit(10)
      data_set.each do |i|
        gon.xdata << [i.name]
        gon.y1data << [i.total_rating_avg.to_f]
        gon.y2data << [i.rating_count]
      end
    end
  end
  
  private
  
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/analysis_helper.rb
module AnalysisHelper
end

app/views/analysis/new.html.erb
<% provide(:title, 'Analysis') %>
<h1>Select a data analysis graph</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_tag show_analysis_path do %>
      
      <div class="radio">
        <ul>
          <%= radio_button_tag :choice, "best_beer", true, class: "analysis" %>
          <%= label_tag :choice_best_beer, 'Top 10 Best Rated Beers' %>
        </ul>
        <ul>
          <%= radio_button_tag :choice, "worst_beer", false, class: "analysis" %>
          <%= label_tag :choice_worst_beer, 'Bottom 10 Worst Rated Beers' %>
        </ul>
        <ul>
          <%= radio_button_tag :choice, "most_rated_beer", false, class: "analysis" %>
          <%= label_tag :choice_most_rated_beer, 'Top 10 Most Rated Beers' %>
        </ul>
        <ul>
          <%= radio_button_tag :choice, "best_rated_1_beer", false, class: "analysis" %>
          <%= label_tag :choice_best_rated_1_beer, 'Top 10 Beers With the Best First Impression' %>
        </ul>
        <ul>
          <%= radio_button_tag :choice, "best_rated_2_beer", false, class: "analysis" %>
          <%= label_tag :choice_best_rated_2_beer, 'Top 10 Beers With the Best Taste Rating' %>
        </ul>
        <ul>
          <%= radio_button_tag :choice, "best_rated_3_beer", false, class: "analysis" %>
          <%= label_tag :choice_best_rated_3_beer, 'Top 10 Beers With the Best After-taste' %>
        </ul>
        <ul>
          <%= radio_button_tag :choice, "combo_rated", false, class: "analysis" %>
          <%= label_tag :choice_combo_rated, 'Combo Graph: Top Rated based on Average Rating vs Times Rated' %>
        </ul>
        <ul>
          <%= radio_button_tag :choice, "combo_rated_reversed", false, class: "analysis" %>
          <%= label_tag :choice_combo_rated_reversed, 'Combo Graph: Top Rated based on Times Rated vs Average Rating' %>
        </ul>
      </div>

      <div class="center">
        <%= submit_tag "Generate Graph", class: "btn btn-primary analysis" %>
      </div>
    <% end %>
  </div>
</div>

app/views/analysis/show.html.erb
<div id="<%= @chart_type %>" style="width:100%; height:400px;"></div>