config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get  'help' => 'static_pages#help'
  get  'about' => 'static_pages#about'
  get  'contact' => 'static_pages#contact'
  get  'signup' => 'users#new'
  get  'rate' => 'ratings#new'
  get  'add_beer' => 'beers#new'
  get  'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get  'new_analysis' => 'analysis#new'
  get  'show_analysis' => 'analysis#show'
  post  'show_analysis' => 'analysis#show'
  resources :users
  resources :ratings
  resources :beers do
    collection { post:import}
  end
end

app/models/beer.rb
class Beer < ActiveRecord::Base
  
  def self.import(file)
    beer_import_array = []
    CSV.foreach(file.path, headers: true) do |row|
      @beer = Beer.create!(row.to_hash)
      beer_import_array << @beer.id
    end
    beer_import_array
  end
  
  has_many :ratings, dependent: :destroy
  has_many :recommenders, dependent: :destroy
  mount_uploader :image_path, BeerImageUploader
  validates :name, presence: true, uniqueness: { case_sensitive: false }
  validates :style, presence: true
  validates :original_gravity, presence: true
  validates :final_gravity, presence: true
  validates :abv, presence: true
  validates :ibu, presence: true
  validates :srm, presence: true

  def self.search(search, hide_rated, user_id)
    
    if !search.blank? && hide_rated
      where("name LIKE ? AND recommenders.has_rated = ? AND recommenders.user_id = ?", "%#{search}%", FALSE, user_id)
    elsif !search.blank? && !hide_rated
      where("name LIKE ? AND recommenders.user_id = ?", "%#{search}%", user_id)
    elsif search.blank? && hide_rated
      where("recommenders.has_rated = ? AND recommenders.user_id = ?", FALSE, user_id)
    else
      where("recommenders.user_id = ?", user_id)
    end
  end
end

app/controllers/beers_controller.rb
class BeersController < ApplicationController
  before_action :logged_in_user, only: [:index,:show]
  before_action :admin_user,     only: [:destroy, :update]
  
  def new
    @beer = Beer.new
  end

  def import
    beer_import_array = Beer.import(params[:file])
    beer_import_array.each do |i|
      update_recommend_matrix_new_beer(i)
    end
    flash[:success] = "Beers added successfully"
    redirect_to beers_path
  end

  def show
    @beer = Beer.find(params[:id])
    unless current_user.ibu.nil? 
      @percentage = 0
    end
  end
  
  def edit
    @beer = Beer.find(params[:id])
  end
  
  def update
    @beer = Beer.find(params[:id])
    if @beer.update_attributes(beer_params)
      flash[:success] = "Beer updated"
      redirect_to @beer
    else
      render 'edit'
    end
  end
  
  def destroy
    Beer.find(params[:id]).destroy
    flash[:success] = "Beer deleted"
    redirect_to beers_path
  end

  def index
	    @beers = Beer.joins(:recommenders).search(params[:search], params[:hide_rated], current_user.id).order(name: :ASC).paginate(:per_page => 16, page: params[:page])
  end

  def create
    @beer = Beer.new(beer_params)
    if @beer.save
      update_recommend_matrix_new_beer(@beer.id)
      flash[:success] = "Beer successfully saved!"
      redirect_to @beer
    else

      render 'new'
    end
  end
  
  private

    # Confirms a logged-in user.
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end
    
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
  
    def beer_params
      params.require(:beer).permit(:name, :style, :original_gravity, :final_gravity, :abv, :ibu, :srm, :image_path)
    end
end

app/helpers/beers_helper.rb
module BeersHelper
end

app/views/beers/_beer.html.erb
<div class = "center"><%= will_paginate %></div>
<% @beers.each_slice(4) do |beers| %>
  <div class="row">
    <% beers.each do |beer| %>
      <%= link_to (beer) do %>
      <div class="col-md-3 col-sm-3 col-xs-12">
        <div class="beer_index">
          <ul><%= image_tag(beer.image_path_url, class: "img-responsive", alt: "Beer Image") %></ul>
          <strong><ul class="center beer_title"><%= beer.name %></ul></strong>
          <em><ul class="center"><%= beer.style %></ul></em>
          <ul class="center beer_percentage"><%= number_to_percentage(beer.recommenders.where(user_id: current_user.id).first.beer_percentage, precision: 2) %> Match</ul>
        </div>
      </div>
      <% end %>
    <% end %>
  </div>
<% end %>
<div class = "center"><%= will_paginate %></div>

app/views/beers/edit.html.erb
<% provide(:title, 'Edit Beer') %>

<h1>Edit Beer</h1>


<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @beer, :html => {:multipart => true} do |f| %>
      <%= render 'shared/beer_error_messages' %>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :style %>
      <%= f.text_field :style %>

      <%= f.label :original_gravity %>
      <%= f.text_field :original_gravity %>

      <%= f.label :final_gravity %>
      <%= f.text_field :final_gravity %>
      
      <%= f.label :abv %>
      <%= f.text_field :abv %>
      
      <%= f.label :ibu %>
      <%= f.text_field :ibu %>
      
      <%= f.label :srm %>
      <%= f.text_field :srm %>
      
      <%= f.file_field :image_path %>
     
     
      <%= f.submit "Update Beer", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/beers/index.html.erb
<% provide(:title, 'All beers') %>
<h1>All Beers</h1>

<div class="center">
  <%= form_tag beers_path, :method => 'get', id: "beers_search", class:"form-inline" do |f| %>
    <div class="form-group">
      <%= label_tag(:hide_rated, "Hide rated beers") %>
      <%= check_box_tag( :hide_rated, 1, params[:hide_rated], class: "form-control") %> <br />
      
      <%= label_tag :search, "Search" %>
      <%= text_field_tag :search, params[:search], class: "form-control" %>
    </div>
  <% end %>
</div>

<div id="beers">
  <%= render 'beer.html.erb' %>
</div>

app/views/beers/index.js.erb
$("#beers").html("<%= escape_javascript(render("beer.html.erb")) %>")

app/views/beers/new.html.erb
<h1>Add New Beer</h1>

<% provide(:title, 'Add New Beer to Rate') %>


<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @beer, :html => {:multipart => true} do |f| %>
      <%= render 'shared/beer_error_messages' %>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :style %>
      <%= f.text_field :style %>

      <%= f.label :original_gravity %>
      <%= f.text_field :original_gravity %>

      <%= f.label :final_gravity %>
      <%= f.text_field :final_gravity %>
      
      <%= f.label :abv %>
      <%= f.text_field :abv %>
      
      <%= f.label :ibu %>
      <%= f.text_field :ibu %>
      
      <%= f.label :srm %>
      <%= f.text_field :srm %>
      
      <%= f.file_field :image_path %>
     
     
      <%= f.submit "Add to beer database", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

<div class="col-md-6 col-md-offset-3">
  <div class="row">
    <br>
  <h1 class="center">Import from CSV</h1>
  <br>
  <%= form_tag import_beers_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Upload Beer CSV", class: "btn btn-primary"%>
  <% end %>
  </div>
</div>

app/views/beers/show.html.erb
<% provide(:title, @beer.name) %>
<div class="row">
  <div class="col-md-4 col-md-push-1 center">
    <div class="beer_header">
      <%= image_tag(@beer.image_path_url, alt: "Beer Image", class:"img-responsive") %>
    </div>
   </div>
   <div class="col-md-5 col-md-push-2 beer_info center">
     <h2 class="beer_title"><%= @beer.name %></h2>
     Style: <%= @beer.style %>
     <br>
     Original Gravity: <%= @beer.original_gravity %>
     <br>
     Final Gravity: <%= @beer.final_gravity %>
     <br>
     ABV: <%= @beer.abv %>
     <br>
     IBU: <%= @beer.ibu %>
     <br>
     SRM: <%= @beer.srm %>
     <br>
     Percentage: <%= number_to_percentage(@beer.recommenders.where(user_id: current_user.id).first.beer_percentage, precision: 2) %>
     <p class="center">
        <%= link_to "Rate Beer", rate_path(:beer_id => @beer.id), class: "btn btn-lg btn-primary" %>
     </p>
     <% if current_user.admin? %>
       <p class="center">
         <%= link_to "Edit", edit_beer_path(@beer.id) %> | <%= link_to "Delete", @beer, method: :delete, data: { confirm: "You sure?" } %>
       </p>
     <% end %>
	</div>

</div>