config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get  'help' => 'static_pages#help'
  get  'about' => 'static_pages#about'
  get  'contact' => 'static_pages#contact'
  get  'signup' => 'users#new'
  get  'rate' => 'ratings#new'
  get  'add_beer' => 'beers#new'
  get  'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get  'new_analysis' => 'analysis#new'
  get  'show_analysis' => 'analysis#show'
  post  'show_analysis' => 'analysis#show'
  resources :users
  resources :ratings
  resources :beers do
    collection { post:import}
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav class="nav navbar-fixed-bottom navbar-inverse">
    <ul>
      <li><a href=<%= contact_path %>><span class="fa fa-envelope-o fa-lg"></span>  Contact</a></li>
      <li><a href=<%= about_path %>><span></span>  About</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-fixed-top navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <li><a class="navbar-brand" href=<%= root_path %>><span class="fa fa-lg"></span>CBR</a></li>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-left">
        <li><a href=<%= root_path %>><span class="fa fa-home fa-lg"></span> Home</a></li>
      </ul>
        <% if logged_in? %>
         <ul class="nav navbar-nav navbar-right">
          
          <li><%= link_to "Browse Beers", beers_path %></li>
          <% if current_user.admin? %>
            <li class="dropdown">
              <a href='#' class="dropdown-toggle" data-toggle="dropdown">Admin<b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><%= link_to "Users", users_path %></li>
                <li><%= link_to "Add Beer", add_beer_path %></li>
                <li><%= link_to "Ratings Analysis", new_analysis_path %></li>
                <li><%= link_to "Ratings Management", ratings_path %></li>
              </ul>
            </li>
          <% end %>
          <li class="dropdown">
            <a href='#' class="dropdown-toggle" data-toggle="dropdown">Account <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
            </ul>
          </li>
          <li><a href=<%= logout_path %> data-method="delete"><span class="fa fa-sign-out fa-lg"></span>  Logout</a></li>
         </ul>
        <% else %>
        <ul class="nav navbar-nav navbar-right">
            <li><a href=<%= signup_path %>><span class="fa fa-user fa-lg"></span>  Sign Up</a></li>
            <li><a href=<%= login_path %>><span class="fa fa-sign-in fa-lg"></span>  Login</a></li>
        </ul>
        <% end %>
    </div>
  </div>
</nav>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= include_gon(:init => true) %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track'=> true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track'=> true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
    <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <script src="//code.highcharts.com/highcharts.js"></script>
  </head>
  <body>
    <div class="container">
    <%= render 'layouts/header' %>
      <div class="container-fluid" id="main-content">
        <% flash.each do |message_type, message| %>
          <div class="alert alert-<%= message_type %>"><%= message %></div>
        <% end %>
        <%= yield %>
      </div>
        <%= render 'layouts/footer' %>
        <%= debug(params) if Rails.env.development? %>
    </div>
    <br><br>
  </body>
</html>